_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.8.19
            "5": 0.19.8
            "6": 4.44.2
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
